In [2]:
import clean_data_svi as cds
import supervised as sup
import pathlib
import keras_model as km
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
from datetime import timedelta, datetime
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tqdm import tqdm
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Activation, Dense, LSTM
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error, median_absolute_error, roc_curve, auc, f1_score, precision_recall_curve, r2_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix

Using TensorFlow backend.


In [3]:
SVI_list = []
for i in range(4):
    df = pd.read_csv(f"clean_tables/svi_{i+1}.csv", index_col="date")
    df = df.drop(columns=['Settling_velocity', 'SV_label', 'SVI_label'])
    df.index = pd.to_datetime(df.index, dayfirst=True)
    SVI_list.append(df)

In [4]:
temp_df = pd.read_csv("clean_tables/temperatur.csv", index_col="date")
temp_df.index = pd.to_datetime(temp_df.index, dayfirst=True)
sludge_age_df = pd.read_csv("clean_tables/sludge_age_f_m.csv", index_col="date")
sludge_age_df.index = pd.to_datetime(sludge_age_df.index, dayfirst=True)

In [5]:
reactor_list = []
for i in range(4):
    join = pd.concat([SVI_list[i], temp_df], axis=1)
    if i <=1:
        join = pd.concat([join, sludge_age_df.iloc[:, np.r_[0, 2]]], axis=1)
    else:
        join = pd.concat([join, sludge_age_df.iloc[:, np.r_[1, 3]]], axis=1)
    join.columns = ['SVI', 'Temperature', 'F_M', 'Sludge Age']
    reactor_list.append(join)

In [6]:
reactor_list[0]

SVI  Temperature   F_M  Sludge Age
date                                                 
2010-01-01   90.943683       22.030  0.23        3.44
2010-01-02   84.365325       21.985  0.18        3.78
2010-01-03   94.541139       21.740  0.21        3.82
2010-01-04   97.402597       21.815  0.21        3.40
2010-01-05  107.937685       21.890  0.23        3.70
...                ...          ...   ...         ...
2020-12-27  166.666667       22.540  0.25        2.75
2020-12-28  147.453083       22.535  0.26        2.91
2020-12-29  154.702970       22.660  0.26        2.82
2020-12-30  159.722222       22.660  0.27        2.91
2020-12-31  167.597765       22.735  0.27        2.91

[4018 rows x 4 columns]

In [7]:
micro_list = []
for i in range(4):
    df = pd.read_csv(f"clean_tables/micro_{i+1}.csv", index_col="date")
    df.index = pd.to_datetime(df.index, dayfirst=True)
    micro_list.append(df)

In [8]:
micro_list[0]

arcella  nude ameba  aspidisca  trachelopylum  lionutus  \
date                                                                  
2010-02-18     40.0         4.0        2.0            0.0       6.0   
2010-03-02     27.0         5.0        3.0            1.0      16.0   
2010-03-08     27.0         8.0       14.0            1.0       9.0   
2010-03-18     11.0        12.0        2.0            0.0      16.0   
2010-04-08     12.0         6.0       10.0            0.0      13.0   
...             ...         ...        ...            ...       ...   
2020-09-23      5.0        11.0        9.0            2.0       5.0   
2020-10-21      7.0        57.0       55.0            0.0      12.0   
2020-10-28     14.0        20.0        1.0            0.0      24.0   
2020-11-11     23.0        86.0       17.0            1.0      29.0   
2020-11-25     12.0        56.0       64.0            0.0      18.0   

            paramecium  carchecium  epistylis  opercularia  podophyra  ...  \
date                                                                   ...   
2010-02-18         0.0         1.0        4.0          4.0        0.0  ...   
2010-03-02         0.0         0.0       13.0          4.0        0.0  ...   
2010-03-08         1.0         0.0       11.0          9.0        0.0  ...   
2010-03-18         0.0         0.0        7.0          0.0        0.0  ...   
2010-04-08         1.0         0.0        1.0          1.0        0.0  ...   
...                ...         ...        ...          ...        ...  ...   
2020-09-23         0.0         0.0        6.0          0.0        3.0  ...   
2020-10-21         0.0        14.0       26.0          0.0        0.0  ...   
2020-10-28         0.0         0.0       35.0          2.0        0.0  ...   
2020-11-11         0.0         0.0       18.0          0.0        0.0  ...   
2020-11-25         0.0         0.0       41.0          4.0        2.0  ...   

            Floc Strength  Indian Ink  Filament index  Floc_size_small  \
date                                                                     
2010-02-18            NaN         NaN             3.0              0.0   
2010-03-02            NaN         NaN             3.0              NaN   
2010-03-08            NaN         NaN             3.0              NaN   
2010-03-18            NaN         NaN             3.0              0.0   
2010-04-08            NaN         NaN             3.0              0.0   
...                   ...         ...             ...              ...   
2020-09-23            3.0         1.0             2.0              0.0   
2020-10-21            1.0         3.0             3.0              1.0   
2020-10-28            2.0         3.0             2.5              1.0   
2020-11-11            3.0         2.0             2.5              1.0   
2020-11-25            1.0         2.0             2.5              1.0   

            Floc_size_medium  Floc_size_large  Shape_close  Shape_open  \
date                                                                     
2010-02-18               1.0              1.0          0.0         1.0   
2010-03-02               NaN              NaN          0.0         1.0   
2010-03-08               NaN              NaN          1.0         1.0   
2010-03-18               1.0              1.0          0.0         1.0   
2010-04-08               1.0              1.0          0.0         1.0   
...                      ...              ...          ...         ...   
2020-09-23               1.0              1.0          1.0         1.0   
2020-10-21               1.0              1.0          0.0         1.0   
2020-10-28               1.0              1.0          1.0         1.0   
2020-11-11               1.0              1.0          1.0         1.0   
2020-11-25               1.0              1.0          0.0         1.0   

            Filaments_in_floc  Free_filaments  
date                                           
2010-02-18                1.0             1.0  
201

In [9]:
join_list = []
for i in range(4):
    join = pd.concat([reactor_list[i], micro_list[i]], axis=1)
    join_list.append(join)

In [19]:
join_list[1]

SVI  Temperature   F_M  Sludge Age  arcella  nude ameba  \
date                                                                         
2010-01-01   88.649852       22.030  0.23        3.44      NaN         NaN   
2010-01-02   86.480363       21.985  0.18        3.78      NaN         NaN   
2010-01-03   96.370968       21.740  0.21        3.82      NaN         NaN   
2010-01-04  109.427609       21.815  0.21        3.40      NaN         NaN   
2010-01-05  100.929054       21.890  0.23        3.70      NaN         NaN   
...                ...          ...   ...         ...      ...         ...   
2020-12-27  159.420290       22.540  0.25        2.75      NaN         NaN   
2020-12-28  147.887324       22.535  0.26        2.91      NaN         NaN   
2020-12-29  152.173913       22.660  0.26        2.82      NaN         NaN   
2020-12-30  148.725212       22.660  0.27        2.91      NaN         NaN   
2020-12-31  152.777778       22.735  0.27        2.91      NaN         NaN   

            aspidisca  trachelopylum  lionutus  paramecium  ...  \
date                                                        ...   
2010-01-01        NaN            NaN       NaN         NaN  ...   
2010-01-02        NaN            NaN       NaN         NaN  ...   
2010-01-03        NaN            NaN       NaN         NaN  ...   
2010-01-04        NaN            NaN       NaN         NaN  ...   
2010-01-05        NaN            NaN       NaN         NaN  ...   
...               ...            ...       ...         ...  ...   
2020-12-27        NaN            NaN       NaN         NaN  ...   
2020-12-28        NaN            NaN       NaN         NaN  ...   
2020-12-29        NaN            NaN       NaN         NaN  ...   
2020-12-30        NaN            NaN       NaN         NaN  ...   
2020-12-31        NaN            NaN       NaN         NaN  ...   

            Floc Strength  Indian Ink  Filament index  Floc_size_small  \
date                                                                     
2010-01-01            NaN         NaN             NaN              NaN   
2010-01-02            NaN         NaN             NaN              NaN   
2010-01-03            NaN         NaN             NaN              NaN   
2010-01-04            NaN         NaN             NaN              NaN   
2010-01-05            NaN         NaN             NaN              NaN   
...                   ...         ...             ...              ...   
2020-12-27            NaN         NaN             NaN              NaN   
2020-12-28            NaN         NaN             NaN              NaN   
2020-12-29            NaN         NaN             NaN              NaN   
2020-12-30            NaN         NaN             NaN              NaN   
2020-12-31            NaN         NaN             NaN              NaN   

            Floc_size_medium  Floc_size_large  Shape_close  Shape_open  \
date                                                                     
2010-01-01               NaN              NaN          NaN         NaN   
2010-01-02               NaN              NaN          NaN         NaN   
2010-01-03               NaN              NaN          NaN         NaN   
2010-01-04               NaN              NaN          NaN         NaN   
2010-01-05               NaN              NaN          NaN         NaN   
...                      ...              ...          ...         ...   
2020-12-27               NaN              NaN          NaN         NaN   
2020-12-28               NaN              NaN          NaN         NaN   
2020-12-29               NaN              NaN          NaN         NaN   
2020-12-30               NaN              NaN          NaN         NaN   
2020-12-31               NaN              NaN          NaN         NaN   

            Filaments_in_floc  Free_filaments  
date                                           
2010-01-01                NaN             NaN  
2010-01-02                NaN             NaN  
2010-01-03    

In [20]:
X, Y = km.create_join_x_y_arr(join_list, n_steps_in=7, binary=True)

In [21]:
X

array([[[ 90.94368341,  22.03      ,   0.23      , ...,          nan,
                  nan,          nan],
        [ 84.36532508,  21.985     ,   0.18      , ...,          nan,
                  nan,          nan],
        [ 94.54113924,  21.74      ,   0.21      , ...,          nan,
                  nan,          nan],
        ...,
        [107.93768546,  21.89      ,   0.23      , ...,          nan,
                  nan,          nan],
        [ 89.8744113 ,  21.73      ,   0.2       , ...,          nan,
                  nan,          nan],
        [ 94.62809917,  21.655     ,   0.21      , ...,          nan,
                  nan,          nan]],

       [[ 84.36532508,  21.985     ,   0.18      , ...,          nan,
                  nan,          nan],
        [ 94.54113924,  21.74      ,   0.21      , ...,          nan,
                  nan,          nan],
        [ 97.4025974 ,  21.815     ,   0.21      , ...,          nan,
                  nan,          nan],
        ...,


In [112]:
X.shape

(16044, 7, 41)

In [114]:
X_normalize, Y_normalize, scalers = km.normalize(X, Y)

100%|████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 20.26it/s]


In [116]:
X_normalize = np.nan_to_num(X_normalize, nan=-1)

In [118]:
X[0]

array([[0.17449926, 0.37586548, 0.3255814 , 0.27717391,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan],
       [0.15989432, 0.37289812, 0.20930233, 0.32336957,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        nan,        nan,        nan,        nan,
               nan,        

In [119]:
Y[0]

array([78.85674931])